version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: name_url_status_checker_db
            POSTGRES_USER: user_url_status_checker_db
            POSTGRES_PASSWORD: f4mXiEVasjk!asS%%NNN6R@K%S?!fODtJ&TD1k2!0:*pFu!UpTm@3p
        volumes:
            - ../pgdb:/var/lib/postgresql/data

#    app:
#        container_name: url_status_checker_web
#        build:
#            context: .
#            dockerfile: Dockerfile
#        env_file: .env
#        ports:
#            - "8000:8000"
#        restart: always
#        links:
#            - postgres
#        depends_on:
#            - "postgres"
#        volumes:
#            - .:/app
#        command: bash -c " source /venv/bin/activate && python /app/manage.py makemigrations --merge && python /app/manage.py makemigrations --noinput && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
